---
interfaces:
  - name: "ethernet-1/1"
    desc: "Edge connection to access1"
    ip: "172.20.20.101/30"
  
  - name: "ethernet-1/2"
    desc: "Edge connection to access2"
    ip: "172.20.20.109/30"

  - name: "ethernet-1/3"
    desc: "Edge connection to Core with link 1"
    ip: "172.20.20.114/30"

  - name: "ethernet-1/4"
    desc: "Edge connection to Core with link 2"
    ip: "172.20.20.118/30"

  - name: "system0"
    desc: "System IP"
    ip: "172.20.20.8/32"

routes:
  - prefix: "172.20.20.6/32"
    nexthop_name: "ToAccess1"
    index: "1"
    nexthop_ip: "172.20.20.102"

  - prefix: "172.20.20.7/32"
    nexthop_name: "ToAccess2"
    index: "1"
    nexthop_ip: "172.20.20.110"

  - prefix: "172.20.20.9/32"
    nexthop_name: "ToCore"
    index: "1"
    nexthop_ip: "172.20.20.113"

  - prefix: "172.20.20.9/32"
    nexthop_name: "ToCore"
    index: "2"
    nexthop_ip: "172.20.20.117"
